version: '3.3'

services:
  db:
    image: postgres:10
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle

  nginx:
    depends_on:
      - moodle
    image: moodle_nginx:latest
    ports:
      - "80:80"
    volumes:
      - moodle:/var/www/moodle
    restart: always

  moodle:
    depends_on:
      - db
    ports:
      - "9000:9000"
    image: moodle_fpm:latest
    volumes:
      - data:/var/www/moodledata
      - moodle:/var/www/moodle
    restart: always

volumes:
    dbdata:
    data:
    moodle: